version: '3.3'
services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    container_name: mongodb
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=1234