version: "3.3"

services:

  auth-server:
    image: jboss/keycloak
    container_name: keycloak
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=localhost:5432
      - DB_DATABASE=university-scheduler
      - DB_SCHEMA=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
      - KEYCLOAK_LOGLEVEL=DEBUG
      - PROXY_ADDRESS_FORWARDING=true
      - DEBUG_PORT=*:8787
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - 8087:8080
      - 8787:8787