spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/university-scheduler
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    consumer:
      group-id: subject
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092